# === scar-ports: Central Port Registry ===
#
# 프로젝트별 포트를 중앙 레지스트리에서 순차 할당 & 관리
# cd 할 때 자동 등록 + env var export
#
# 사용법:
#   devports             현재 프로젝트 포트 확인 & export
#   devports my-app      특정 프로젝트 포트 확인
#   devports-env         .env.ports 파일 생성
#   devports-set N       현재 프로젝트 offset 수동 지정
#   ports                전체 포트 맵 + 실시간 상태
#   ports-active         현재 리스닝 중인 포트
#
# 포트 규칙:
#   FRONT (PORT) = 3000 + offset
#   BACK         = 4000 + offset
#   DB           = 5500 + offset
#
# 레지스트리: ~/.config/scar-ports.conf

SCAR_PORTS_REGISTRY="${SCAR_PORTS_REGISTRY:-$HOME/.config/scar-ports.conf}"
SCAR_DEV_DIR="${SCAR_DEV_DIR:-$HOME/DEV}"

# ── Internal ─────────────────────────────────────────────

# 프로젝트 이름 추출 (~/DEV/ 하위 1단계)
_scar_project_name() {
  local dir="${1:-$PWD}"
  if [[ "$dir" == "$SCAR_DEV_DIR/"* ]]; then
    echo "${dir#$SCAR_DEV_DIR/}" | cut -d/ -f1
  else
    basename "$dir"
  fi
}

# 다음 사용 가능한 offset 찾기 (1부터 순차)
_scar_next_offset() {
  local -A used
  if [[ -f "$SCAR_PORTS_REGISTRY" ]]; then
    while IFS='=' read -r name offset; do
      [[ "$name" =~ ^[[:space:]]*# || -z "$name" ]] && continue
      used[$offset]=1
    done < "$SCAR_PORTS_REGISTRY"
  fi

  local i=1
  while [[ -n "${used[$i]}" ]]; do
    ((i++))
  done
  echo "$i"
}

# 레지스트리에 안전하게 append (trailing newline 보장)
_scar_registry_append() {
  local entry="$1"
  mkdir -p "$(dirname "$SCAR_PORTS_REGISTRY")"
  if [[ -f "$SCAR_PORTS_REGISTRY" && -s "$SCAR_PORTS_REGISTRY" ]]; then
    # 마지막 문자가 개행이 아니면 개행 추가
    if [[ "$(tail -c 1 "$SCAR_PORTS_REGISTRY" | wc -l)" -eq 0 ]]; then
      echo "" >> "$SCAR_PORTS_REGISTRY"
    fi
  fi
  echo "$entry" >> "$SCAR_PORTS_REGISTRY"
}

# 레지스트리에서 프로젝트 항목 제거 (fixed-string 매칭)
_scar_registry_remove() {
  local name="$1"
  if [[ -f "$SCAR_PORTS_REGISTRY" ]]; then
    local tmp=$(mktemp)
    command grep -vF "${name}=" "$SCAR_PORTS_REGISTRY" | command grep -v "^${name}=" > "$tmp"
    mv "$tmp" "$SCAR_PORTS_REGISTRY"
  fi
}

# 레지스트리에서 프로젝트 offset 조회 (fixed-string 매칭)
_scar_registry_lookup() {
  local name="$1"
  if [[ -f "$SCAR_PORTS_REGISTRY" ]]; then
    command grep -F "${name}=" "$SCAR_PORTS_REGISTRY" 2>/dev/null | command grep "^${name}=" | head -1 | cut -d= -f2
  fi
}

# 프로젝트의 offset 조회 (미등록이면 자동 등록)
_scar_port_offset() {
  local name="$1"

  # 레지스트리에서 조회
  local offset=$(_scar_registry_lookup "$name")
  if [[ -n "$offset" ]]; then
    echo "$offset"
    return
  fi

  # 미등록 → 자동 등록
  local new_offset=$(_scar_next_offset)
  _scar_registry_append "${name}=${new_offset}"
  echo "$new_offset"
}

# ── Commands ─────────────────────────────────────────────

# 현재 프로젝트 포트 확인 & export
devports() {
  local name
  if [[ -n "$1" ]]; then
    name="$1"
  else
    if [[ "$PWD" != "$SCAR_DEV_DIR/"* ]]; then
      echo "Not inside $SCAR_DEV_DIR. Use: devports <project-name>"
      return 1
    fi
    name=$(_scar_project_name)
  fi
  local o=$(_scar_port_offset "$name")

  export PORT=$((3000 + o))
  export PORT_FRONT=$PORT
  export PORT_BACK=$((4000 + o))
  export PORT_DB=$((5500 + o))

  printf "\033[1;36m%s\033[0m (offset: %s)\n" "$name" "$o"
  printf "  PORT (FRONT) : \033[33m%s\033[0m\n" "$PORT_FRONT"
  printf "  BACK         : \033[33m%s\033[0m\n" "$PORT_BACK"
  printf "  DB           : \033[33m%s\033[0m\n" "$PORT_DB"
}

# offset 수동 지정 (1-999)
devports-set() {
  local offset="$1"
  if [[ -z "$offset" || ! "$offset" =~ ^[0-9]+$ || "$offset" -eq 0 || "$offset" -gt 999 ]]; then
    echo "Usage: devports-set <offset>  (1-999)"
    echo "  예: devports-set 20  → FRONT=3020, BACK=4020, DB=5520"
    return 1
  fi

  if [[ "$PWD" != "$SCAR_DEV_DIR/"* ]]; then
    echo "Not inside $SCAR_DEV_DIR."
    return 1
  fi

  local name=$(_scar_project_name)
  mkdir -p "$(dirname "$SCAR_PORTS_REGISTRY")"

  # 충돌 체크
  if [[ -f "$SCAR_PORTS_REGISTRY" ]]; then
    local existing=$(command grep "=${offset}$" "$SCAR_PORTS_REGISTRY" 2>/dev/null | head -1 | cut -d= -f1)
    if [[ -n "$existing" && "$existing" != "$name" ]]; then
      printf "\033[31m⚠ offset %s는 %s가 사용 중\033[0m\n" "$offset" "$existing"
      return 1
    fi
  fi

  # 기존 항목 제거 후 재등록
  _scar_registry_remove "$name"
  _scar_registry_append "${name}=${offset}"

  devports "$name"
}

# .env.ports 파일 생성
devports-env() {
  if [[ "$PWD" != "$SCAR_DEV_DIR/"* ]]; then
    echo "Not inside $SCAR_DEV_DIR."
    return 1
  fi
  local name=$(_scar_project_name)
  local o=$(_scar_port_offset "$name")
  local front=$((3000 + o)) back=$((4000 + o)) db=$((5500 + o))

  cat > .env.ports <<EOF
# Auto-generated by scar-ports (project: $name, offset: $o)
PORT=$front
PORT_FRONT=$front
PORT_BACK=$back
PORT_DB=$db
DATABASE_URL=postgresql://postgres:postgres@localhost:$db/\${DB_NAME:-app}
EOF
  echo ".env.ports → front:$front back:$back db:$db"
}

# 전체 포트 맵 + 실시간 상태
ports() {
  # 리스닝 포트 한 번만 조회
  local listening=$(lsof -iTCP -sTCP:LISTEN -P -n 2>/dev/null | awk '{split($9,a,":"); print a[length(a)]}' | sort -u)

  printf "\033[1m%-28s  %-12s %-12s %-12s\033[0m\n" "PROJECT" "FRONT" "BACK" "DB"
  printf "%-28s  %-12s %-12s %-12s\n" "────────────────────────────" "──────────" "──────────" "──────────"

  # 레지스트리에서 읽기 (등록 순서 유지)
  if [[ ! -f "$SCAR_PORTS_REGISTRY" ]]; then
    echo "(레지스트리 비어있음. cd ~/DEV/<project>하면 자동 등록)"
    return
  fi

  local current_name=$(_scar_project_name 2>/dev/null)

  while IFS='=' read -r name offset; do
    [[ "$name" =~ ^[[:space:]]*# || -z "$name" ]] && continue

    local front=$((3000+offset)) back=$((4000+offset)) db=$((5500+offset))

    # 실시간 상태 체크 (inline)
    local f_status=$(echo "$listening" | command grep -qx "$front" && printf "\033[32m●\033[0m" || printf "\033[90m·\033[0m")
    local b_status=$(echo "$listening" | command grep -qx "$back"  && printf "\033[32m●\033[0m" || printf "\033[90m·\033[0m")
    local d_status=$(echo "$listening" | command grep -qx "$db"    && printf "\033[32m●\033[0m" || printf "\033[90m·\033[0m")

    # 현재 프로젝트 하이라이트
    if [[ "$name" == "$current_name" ]]; then
      printf "\033[36m▸ %-26s\033[0m  %s %-9s %s %-9s %s %-9s\n" \
        "$name" "$f_status" "$front" "$b_status" "$back" "$d_status" "$db"
    else
      printf "  %-26s  %s %-9s %s %-9s %s %-9s\n" \
        "$name" "$f_status" "$front" "$b_status" "$back" "$d_status" "$db"
    fi
  done < "$SCAR_PORTS_REGISTRY"
}

# 현재 리스닝 포트
ports-active() {
  printf "\033[1m%-7s %-15s %s\033[0m\n" "PORT" "PROCESS" "PID"
  printf "%-7s %-15s %s\n" "─────" "───────────────" "─────"
  lsof -iTCP -sTCP:LISTEN -P -n 2>/dev/null | \
    awk 'NR>1 {split($9,a,":"); printf "%-7s %-15s %s\n", a[length(a)], $1, $2}' | \
    sort -n -k1 | uniq
}

# 레지스트리에서 프로젝트 제거
devports-rm() {
  local name="${1:-$(_scar_project_name)}"
  _scar_registry_remove "$name"
  echo "Removed: $name"
}

# ── Auto-set on cd ───────────────────────────────────────

_scar_auto_devports() {
  if [[ "$PWD" == "$SCAR_DEV_DIR/"* ]]; then
    local name=$(_scar_project_name)
    local o=$(_scar_port_offset "$name")
    export PORT=$((3000 + o))
    export PORT_FRONT=$PORT
    export PORT_BACK=$((4000 + o))
    export PORT_DB=$((5500 + o))
  fi
}

autoload -U add-zsh-hook
add-zsh-hook chpwd _scar_auto_devports

# 현재 위치에서도 초기화
_scar_auto_devports

# === End scar-ports ===
